---
version: '3'

tasks:
  oas-download:
    desc: Download OpenAPI specification
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/inference-gateway/refs/heads/main/openapi.yaml

  lint:
    desc: Lint the SDK
    cmds:
      - npm run lint

  build:
    desc: Build the SDK
    cmds:
      - npm run build

  test:
    desc: Run tests
    cmds:
      - npm run test

  generate-types:
    desc: Generate TypeScript types from OpenAPI specification
    cmds:
      - npx openapi-typescript openapi.yaml --enum --enum-values --dedupe-enums=true --root-types -o src/types/generated/index.ts
      - npx prettier --write src/types/generated/index.ts
