---
version: "3"

tasks:
  oas-download:
    desc: Download OpenAPI specification
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/inference-gateway/refs/heads/main/openapi.yaml

  lint:
    desc: Lint the SDK
    cmds:
      - npm run lint

  build:
    desc: Build the SDK
    cmds:
      - npm run build

  test:
    desc: Run tests
    cmds:
      - npm run test
