schema-version = "1.11.0"

[install]
nodejs_24.pkg-path = "nodejs_24"
nodejs_24.version = "^24.14.1"
nodejs_24.outputs = "all"
claude-code.pkg-path = "claude-code"
claude-code.version = "^2.1.148"
prettier.pkg-path = "prettier"
prettier.version = "^3.8.3"
markdownlint-cli.pkg-path = "markdownlint-cli"
markdownlint-cli.version = "^0.48.0"
go-task.pkg-path = "go-task"
go-task.version = "3.48.0"
infer.flake = "github:inference-gateway/cli/v0.112.0"
